def matching_letters(c1, c2, shift):
    sum = 0
    for i in range(0, len(c2) - shift):
        if c1[i] == c2[i + shift]:
            sum = sum + 1
    return sum

c1 = "UMTWQWUASQSQTMWGYMJISDALKGPVPZWDUTRVTWHPGZOAVWOQDIDKLSENUVRPAFBWIGDVZQGZMJMFYGAYJEMKEFPVZXZUVRTSDBTGMXICXGUVEIJQAEQWAVDLGDMKMLTWFKZFQHSMXLDEAXIMSMFIWMLFTPEFPAPILTMHELQZJTSDBZJLTMHSJXLMMLUALASKQSENQWQHJUDTRYANQXZQAAPWQVLRVDMRYDMBTRYFPPGADKFPSFQZRTIPPRWHMCMXUVOQQEMWJYDWHMFSOCMEMJZYLFPPQGGBSSOTMYINQZTXAEIOEEBHOVALHWCFADPQTQZTREKAZYDAESIFQDPVARQYHEKAPPXUVGSDGVEEJUTJTSGATRYNMQSJQKZJXUVHEJQPZYKQAKEFPJCMFSQYKMBBSIJQICSXQDPVQRCYIJMTTQWQBZEFPMDTWOQLPDKESIFQDPVEKPJTGEOPXKGKSEFGXAIJTIYHGRUPDLTIEMLDMBYADMDEKFZZRYYWCEDBZTRUUXWILAXCINQVEQWRZZQVQTTFWDIEIDKAEIHBQYKAZBZXZQAEVWQBKEFPUPXZALTGSXTJOFAKVMFSXPSHXMTWZMBDSXRLELWZHTEUOWFRLUBSMYTBTQWFWRILFWDISMADSGZIDMUMVMXZUATWEKAFFKFQEYLQNZVHUAESDMVOFSXTMAAFPLTZUTZWGBPTGSXNWSMDQDLUMBZXZDWHWZUUDIDRCASFTQDWOAZOSACCTILXGEECQBZXZQASMHNBSIJQQDRGFPTRYECCTJUATRYUVELAEJTJLTMJFMFSYIOUBKEDYWDXSXTXIFUVELWUZOIYDMPDKAUPXAYMZVGFPPVROPPVAEPGIJKVPEJXGELWEIXIXQMWMFSAESOMZOWLTMZGWMVHMLTUPFLTMCIFAETWQACCMFECWEJOQECGRBSIEMVSELFWPWRNMWXWPZZYFPJJAZMZGIKMATRVUIYMKXMDFQOWCEDDMPJKPKZQEQZNIKGZCSMZLDMLIQELZQZDYJRJCMYTBLRVXMQXRFPPWLDMPXKFIVIQACHELQZHEJPJTXKQFEVWYMOSOZBZAFUAELWNIEXWDGKAZQZPXZMBYSTXMXSDQQDASEPPHTKELZWEHLRVOWZPWPJJFJQMKIKLESMUTIQIOTWFVKBZPZAACDAWDMZYLANDMYTBZJDMVOFDAWVELFPPGJAEOWGRELXWDIRERQZDXZQZPF"
c2 = c1
shifts = [i + 1 for i in range(0, 25)]
frequencies = [matching_letters(c1, c2, shift) for shift in shifts]
# Pair shift values with their frequencies, make it a list, sort that list by their frequencies in descending order
combined = sorted(list(zip(shifts, frequencies)), key=lambda x: x[1], reverse=True)
for pair in combined:
    print("Shift of %2d : %d" % (pair[0], pair[1]))
# Notice how all the multiples of 5 are the most frequent.
# This implies that our key's length is 5.